// Kartu Deep Talk: pertanyaan bawaan buat ngobrol berdua.
// Pakai "aku/kamu" biar bisa dibaca siapa aja yang narik kartunya.
export const TALK_CATS = {
  ringan: { name: 'Ringan', icon: '☀️', color: '#ffb547' },
  kenangan: { name: 'Kenangan', icon: '📸', color: '#ff7eb0' },
  deep: { name: 'Deep Talk', icon: '🌙', color: '#8a5cff' },
  masadepan: { name: 'Masa Depan', icon: '🏡', color: '#3cc4a0' },
  receh: { name: 'Receh & Gombal', icon: '😆', color: '#4aa8f0' },
  custom: { name: 'Dari {pengirim}', icon: '💌', color: '#e8558f' },
};

export const TALK_CARDS = {
  ringan: [
    'Kalau kita bisa liburan besok, mau ke mana?',
    'Makanan apa yang bisa kamu makan tiap hari tanpa bosen?',
    'Lagu apa yang paling sering kamu puter akhir-akhir ini?',
    'Kalau jadi hewan, kamu pengen jadi apa? Kenapa?',
    'Kebiasaan kecil aku yang paling kamu hafal?',
    'Weekend ideal versi kamu kayak gimana?',
    'Film atau series apa yang pengen kamu tonton bareng aku?',
    'Kalau dapet uang 10 juta sekarang, langsung dipakai buat apa?',
    'Pilih: pagi-pagi jalan santai atau malem-malem nongkrong?',
    'Emoji apa yang paling ngegambarin aku?',
    'Kalau kita tukeran badan sehari, hal pertama yang kamu lakuin apa?',
    'Jajanan masa kecil yang paling kamu kangenin?',
    'Hal random apa yang bikin kamu seneng minggu ini?',
    'Kalau bisa punya satu kekuatan super, pengen yang mana?',
    'Tempat makan mana yang pengen kamu cobain bareng aku?',
    'Warna favoritmu apa, dan kenapa?',
    'Hal apa yang paling bikin kamu ketawa akhir-akhir ini?',
    'Pilih: nonton di bioskop atau maraton film di rumah?',
    'Kalau kita bikin kafe berdua, namanya apa?',
    'Nickname buat aku yang belum pernah kamu pakai?',
  ],
  kenangan: [
    'Apa yang kamu pikirin pas pertama kali kenal aku?',
    'Momen kita yang paling pengen kamu ulang?',
    'Chat dari aku yang paling kamu inget?',
    'Kapan kamu mulai sadar kalau kamu suka aku?',
    'Kencan kita yang paling berkesan menurutmu?',
    'Foto kita yang paling kamu suka, dan kenapa?',
    'Momen paling lucu yang pernah kita alamin berdua?',
    'Kado atau hal kecil dari aku yang paling kamu inget?',
    'Berantem pertama kita soal apa? Sekarang kalau diinget gimana?',
    'Lagu apa yang ngingetin kamu sama kita?',
    'Hari paling bahagia yang pernah kamu lewatin sama aku?',
    'Hal apa yang dulu kamu malu buat bilang ke aku?',
    'Kesan pertamamu soal aku, ternyata bener nggak?',
    'Tempat mana yang punya kenangan paling banyak buat kita?',
    'Kapan kamu ngerasa paling deket sama aku?',
    'Hal pertama yang bikin kamu nyaman sama aku?',
    'Kejadian memalukan pas bareng aku yang masih kamu inget?',
    'Obrolan kita yang paling panjang itu soal apa ya?',
    'Hal kecil dari hari pertama kita yang masih kamu inget?',
    'Kalau cerita kita dijadiin film, adegan pembukanya apa?',
  ],
  deep: [
    'Hal apa tentang kamu yang pengen lebih aku ngerti?',
    'Kapan terakhir kali kamu ngerasa sendirian? Apa yang kamu butuhin waktu itu?',
    'Cara aku nunjukin sayang yang paling kamu rasain?',
    'Hal apa dari masa kecilmu yang masih ngaruh ke kamu sekarang?',
    'Apa ketakutan terbesar kamu soal hubungan kita?',
    'Apa yang bikin kamu ngerasa dihargai?',
    'Kalau lagi sedih, kamu pengen aku ngapain?',
    'Hal apa yang lagi kamu perjuangin diam-diam?',
    'Satu hal yang pengen kamu ubah dari diri sendiri?',
    'Kapan kamu paling bangga sama diri kamu?',
    'Hal apa yang bikin kamu susah percaya sama orang?',
    'Apa yang bikin kamu ngerasa aman sama aku?',
    'Ada hal yang pengen kamu omongin tapi belum sempet?',
    'Menurutmu, apa yang bikin hubungan bisa bertahan lama?',
    'Hal apa dari aku yang kadang bikin kamu kepikiran?',
    'Kalau kita lagi berantem, apa yang paling kamu butuhin dari aku?',
    'Satu hal yang pengen lebih sering kamu dengar dari aku?',
    'Apa arti "rumah" buat kamu?',
    'Hal apa yang paling kamu syukurin tahun ini?',
    'Apa yang pengen aku lakuin kalau kamu lagi capek banget?',
  ],
  masadepan: [
    'Kamu ngebayangin kita 5 tahun lagi kayak gimana?',
    'Tempat mana yang pengen kamu datengin bareng aku suatu hari?',
    'Mimpi terbesar kamu apa? Gimana aku bisa bantu?',
    'Rumah impianmu kayak gimana?',
    'Satu kebiasaan baik yang pengen kita mulai bareng?',
    'Kalau punya tabungan bareng, pengen dipakai buat apa dulu?',
    'Tradisi apa yang pengen kita punya tiap tahun?',
    'Kerjaan impianmu kalau semua hal mungkin?',
    'Hal apa yang pengen kamu capai tahun depan?',
    'Kota mana yang pengen kamu tinggalin suatu hari?',
    'Pengen punya peliharaan apa nanti?',
    'Gimana cara kita ngerayain anniversary ke-10?',
    'Hal apa yang pengen kita pelajari bareng?',
    'Kalau bisa kirim pesan ke kita 10 tahun lagi, isinya apa?',
    'Bucket list berdua nomor satu kamu apa?',
    'Kamu pengen jadi orang yang kayak gimana nanti?',
    'Kalau suatu hari kita LDR, gimana cara kita jaga?',
    'Hal kecil apa yang pengen tetap kita lakuin walau udah lama bareng?',
    'Satu mimpi yang belum pernah kamu ceritain ke siapa-siapa?',
    'Apa yang bikin kamu excited soal masa depan kita?',
  ],
  receh: [
    'Gombalin aku sekarang, nggak boleh mikir lama!',
    'Kasih nilai 1–10 buat aku hari ini, terus alasannya 😆',
    'Tiruin cara aku ngambek!',
    'Kalau aku jadi makanan, aku makanan apa?',
    'Sebutin 3 hal yang bikin aku lucu tanpa aku sadar',
    'Pilih: aku tanpa HP seharian atau kamu tanpa jajan seminggu?',
    'Kalau aku jadi penyanyi, judul lagu hit pertamaku apa?',
    'Bikin pantun buat aku sekarang juga!',
    'Kebiasaan aku yang paling nyebelin tapi kamu kangenin?',
    'Kalau kita jadi karakter kartun, kita jadi siapa?',
    'Tebak, aku lagi mikirin apa sekarang?',
    'Kasih aku julukan baru berdasarkan hari ini',
    'Hal teraneh yang pernah kamu googling?',
    'Peragain pose foto andalanmu sekarang!',
    'Siapa yang lebih sering ngambek, kamu atau aku? Jujur!',
    'Kalau aku minta dipeluk jam 2 pagi, respon kamu gimana?',
    'Ucapin "aku sayang kamu" pakai 3 gaya beda',
    'Kalau berantem, siapa yang bakal minta maaf duluan?',
    'Satu kata buat ngegambarin aku hari ini?',
    'Kalau ikut lomba pasangan, kita paling jago lomba apa?',
  ],
};
